BASE_URL = "https://api.binance.com"
KLINES_ENDPOINT = "/api/v3/klines"
pairs = ["BTCUSDT"]
intervals = ["1m", "5m", "15m", "1h", "4h", "1d"]
lookback_days = 40
EQUITY_INDICES = ["^GSPC", "^IXIC"]
DB_NAME = "trading_data.db"
rolling_window = {
    '1m': 10,    # Slightly longer to reduce noise.
    '5m': 7,     # Balanced between sensitivity and smoothing.
    '15m': 10,   # Retain slightly longer period for trend detection.
    '1h': 15,    # Maintain sufficient context for hourly trends.
    '4h': 20,    # Broader window for swing trading.
    '1d': 30,    # Capture larger market trends in daily intervals.
    '1w': 60
}
TIMEFRAME_MAPPING = {  # Define the timeframe hierarchy
    '1m': '5m',
    '5m': '15m',
    '15m': '1h',
    '1h': '4h',
    '4h': '1d',
    '1d': '1w'  # Add more mappings as needed
}
MAX_LAG = 3
SCHEMA_FIELDS = [
    "symbol TEXT",
    "interval TEXT",
    "open_time DATETIME",
    "open REAL",
    "high REAL",
    "low REAL",
    "close REAL",
    "volume REAL",
    "close_time DATETIME",
    "quote_asset_volume REAL",
    "number_of_trades INTEGER",
    "taker_buy_base REAL",
    "taker_buy_quote REAL",
    "ignore INTEGER",
    "High_Low_Diff REAL",
    "Open_Close_Diff REAL",
    "Volatility REAL",
    "Cumulative_Delta_Volume REAL",
    "Relative_Volume REAL",
    "Volume_Shock REAL",
    "Volume_Delta REAL",
    "Z_Score_Volume REAL",
    "Day_of_Week INTEGER",
    "Hour_of_Day INTEGER",
    "Month INTEGER",
    "Quarter INTEGER",
    "Price_Target REAL",
    "Price_Target_Percent REAL",
    "Price_Target_Label INTEGER",
    "Key_Reversal_High INTEGER",
    "Key_Reversal_Low INTEGER",
    "Fractal_High REAL",
    "Fractal_Low REAL",
    "Fractal_High_Binary INTEGER",
    "Fractal_Low_Binary INTEGER",
    "Fractal_High_Count REAL",
    "Fractal_Low_Count REAL",
    "Time_Since_Last_Fractal_High REAL",
    "Time_Since_Last_Fractal_Low REAL",
    "Distance_To_Last_Fractal_High REAL",
    "Distance_To_Last_Fractal_Low REAL",
    "RSI REAL",
    "EMA_20 REAL",
    "EMA_50 REAL",
    "BB_upper REAL",
    "BB_middle REAL",
    "BB_lower REAL",
    "Fisher_Transform REAL",
    "ATR REAL",
    "nATR REAL",
    "Chandelier_Exit REAL",
    "Ichimoku_Tenkan REAL",
    "Ichimoku_Kijun REAL",
    "Ichimoku_Senkou_A REAL",
    "Ichimoku_Senkou_B REAL",
    "PSAR REAL",
    "OBV REAL",
    "MFI REAL",
    "Stoch_K REAL",
    "Stoch_D REAL",
    "Williams_R REAL",
    "CCI REAL",
    "MACD_Line REAL",
    "Signal_Line REAL",
    "MACD_Histogram REAL",
    "ADX REAL",
    "DIpos REAL",
    "DIneg REAL",
    "KC_upper REAL",
    "KC_middle REAL",
    "KC_lower REAL",
    "Supertrend REAL",
    "VWAP REAL",
    "CMF REAL",
    "Cumulative_Volume REAL",
    "Donchian_Upper REAL",
    "Donchian_Lower REAL",
    "Choppiness_Index REAL",
    "Historical_Volatility REAL",
    "Pivot REAL",
    "R1 REAL",
    "S1 REAL",
    "R2 REAL",
    "S2 REAL",
    "Gann_Level_Res_1 REAL",
    "Gann_Level_Sup_1 REAL",
    "Gann_Level_Res_2 REAL",
    "Gann_Level_Sup_2 REAL",
    "Gann_Level_Res_3 REAL",
    "Gann_Level_Sup_3 REAL",
    "Gann_Level_Res_4 REAL",
    "Gann_Level_Sup_4 REAL",
    "Gann_Level_Res_5 REAL",
    "Gann_Level_Sup_5 REAL",
    "Gann_Level_Res_6 REAL",
    "Gann_Level_Sup_6 REAL",
    "Gann_Level_Res_7 REAL",
    "Gann_Level_Sup_7 REAL",
    "ROC_14 REAL",
    "Z_Score REAL",
    "Sharpe_Ratio REAL",
    "Sortino_Ratio REAL",
    "Max_Drawdown REAL",
    "Liquidity_Ratio REAL",
    "Corr_close_volume REAL",
    "Corr_high_low REAL",
    "Corr_close_open REAL",
    "Engulfing INTEGER",
    "Doji INTEGER",
    "Marubozu INTEGER",
    "Three_Line_Strike INTEGER",
    "Lag_1_Close REAL",
    "Lag_1_Volume REAL",
    "Lag_2_Close REAL",
    "Lag_2_Volume REAL",
    "Lag_3_Close REAL",
    "Lag_3_Volume REAL",
    "ATR_Up_Threshold REAL",
    "ATR_Down_Threshold REAL",
    "ATR_Future_Close REAL",
    "ATR_Price_Change REAL",
    "Multi_Class_Label REAL",
    "Swing_High REAL",
    "Swing_Low REAL",
    "Dist_to_SH REAL",
    "Dist_to_SL REAL",
    "Fib_Ratio REAL",
    "Rolling_VWAP REAL",
    "Close_Volume_Corr REAL",
    "Rolling_Mean_Close REAL",
    "Rolling_Std_Close REAL",
    "Rolling_Volume REAL",
    "Future_Close REAL",
    "Trade_Label REAL",
    "level_type TEXT",
    "logic_used TEXT",
    "weighted_score REAL",
    "is_high INTEGER",
    "is_low INTEGER",
#    "fib_retracement REAL",
 #   "fib_retracement_price REAL",
    "higher_timeframe_trend TEXT",
    "higher_timeframe_ma REAL",
    "dynamic_volatility_threshold REAL",
    "PRIMARY KEY (Interval, open_time)"
]
